title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
name: Use Node.js 20
  uses: actions/setup-node@v2
  with:
    node-version: '20'

theme: jekyll-theme-hacker
